### PR TITLE
should EventPoster executeResponseActions as events with response, headers and status

### PR DESCRIPTION
**Pull request by hexmind**

### CODE REVIEW

**Comment by Naitbit** [comment]
Hi. Thanks for contribution. I'll try it out tomorrow and respond, but from quick look, it seems ok. Only potential problem is breaking compatibility of ResponseEvent (because without Java 8, we cannot provide default implementation), but since classes using ResponeEventImpl will still compile it may be acceptable.

**Comment by Naitbit** [comment]
I've merged your pull request  to new branch https://github.com/byoutline/EventCallback/tree/feature/headers_in_events (and updated it with latest changes from develop).

However I've decided that old ResponseEvent is not wrong and therefore I'll not break existing apps that have used this interface directly. (There exist a lot of APIs that do not depend on returned headers and programmers may choose to continue using old ResponseEvent interface for such a cases, to keep their objects cleaner).

To allow access to your functionality I'll refactor your ResponseEvent into new interface instead. Probably it will be called RetrofitResponseEvent and it will extend old ResponseEvent interaface. Obviously that will complicate implementation slightly, but due to library relatively small size I find this trade-off acceptable. Unfortunately I was informed that I may experience internet problems for few days, so probably new version of library will not land on sonatype / maven central before 4th of may. Hope it is ok for you.

**Comment by hexmind** [comment]
Ok, thanks for fast reaction and cooperation. I am waiting for master merge.

**Comment by Naitbit** [comment]
This pull request is included in 1.3.0 snapshot of EventCallback and OttoEventCallback that should already be on Maven central.
`compile 'com.byoutline.eventcallback:eventcallback:1.3.0-SNAPSHOT'`

**Pull request closed without merging**
